name: Deploy Django to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
          if [ -d /home/ubuntu/Github-CI_AWS ]; then
            cd /home/ubuntu/Github-CI_AWS
            if [ -d .git ]; then
              git pull
              sudo docker-compose down
              sudo docker-compose up -d --build
            else
              echo "Not a git repository"
              exit 1
            fi
          else
            echo "Directory does not exist"
            exit 1
          fi
        EOF
